---
- name: Install required python packages
  sudo: True
  pip: name={{ item }} virtualenv={{ vpath }}
  with_items:
   - django==1.3
   - django-tagging
   - twisted
   - graphite-web
   - carbon==0.9.10
   - whisper
  tags:
    - graphite-install
